=== zhufengGNSS/jat_nasa_java/jat/sim/xml/input/sim_input.xsd
<?xml version="1.0"?>
<?altova_samplexml C:\Documents and Settings\rcpage\Desktop\Richard\XML\JAT\sim_input.xml?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="1.0">
	<xs:element name="Input">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="InitialState">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Cartesian">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="x" type="xs:double"/>
										<xs:element name="y" type="xs:double"/>
										<xs:element name="z" type="xs:double"/>
										<xs:element name="xdot" type="xs:double"/>
										<xs:element name="ydot" type="xs:double"/>
										<xs:element name="zdot" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Time">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MJD" type="xs:double"/>
							<xs:element name="t0" type="xs:double"/>
							<xs:element name="tf" type="xs:double"/>
							<xs:element name="dt" type="xs:double"/>
							<xs:element name="thinning" type="xs:double"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Spacecraft">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="CR" type="xs:double"/>
							<xs:element name="cd" type="xs:double"/>
							<xs:element name="area" type="xs:double"/>
							<xs:element name="mass" type="xs:double"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zhufengGNSS/jat_nasa_java/trunk/jat/sim/xml/input/sim_input.xml
<Input xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Code\Jat\jat\xml\input\sim_input.xsd">
	<InitialState>
		<Cartesian>
			<x>-4453.783586</x>
			<y>-5038.203756</y>
			<z>-426.384456</z>
			<xdot>3.831888</xdot>
			<ydot>-2.887221</ydot>
			<zdot>-6.018232</zdot>
		</Cartesian>
	</InitialState>
	<Time>
		<MJD>53157.5</MJD>
		<t0>0</t0>
		<tf>1000</tf>
		<dt>1</dt>
	</Time>
	<Spacecraft>
		<Name>Test</Name>
		<CR>1.000</CR>
		<cd>2.2</cd>
		<area>20</area>
		<mass>1000</mass>
	</Spacecraft>
</Input>
